### ISSUE TITLE
 PyiCloudAPIResponseException('Service Temporarily Unavailable (503)')

### ISSUE THREAD

**Issue by Echoooo0827** [picklepete/pyicloud#456]
## The problem

I ran the program and got a 'Service Temporarily Unavailable (503)' exception

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): Version: 1.0.0
- Last working pyiCloud release (if known): Version: 1.0.0
- Service causing this issue: FindMyPhone
- Python version (`python -V`):  python-3.10.8
- Operating environment (project deps/Docker/Windows/etc.):  windows

## Traceback/Error logs

```shell
Traceback (most recent call last):
  File "C:\Work\Env\python\Lib\site-packages\pyicloud\base.py", line 325, in authenticate
    self.session.post(
  File "C:\Work\Env\python\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Work\Env\python\Lib\site-packages\pyicloud\base.py", line 133, in request
    self._raise_error(response.status_code, response.reason)
  File "C:\Work\Env\python\Lib\site-packages\pyicloud\base.py", line 189, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseException: Service Temporarily Unavailable (503)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Work\pythonProjects\demo\pythonProject\find-my-phone-demo.py", line 3, in <module>
    api = PyiCloudService('****', '*******')
  File "C:\Work\Env\python\Lib\site-packages\pyicloud\base.py", line 271, in __init__
    self.authenticate()
  File "C:\Work\Env\python\Lib\site-packages\pyicloud\base.py", line 333, in authenticate
    raise PyiCloudFailedLoginException(msg, error) from error
pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Service Temporarily Unavailable (503)'))

```

## Checklist

- [ ] I've looked informations into the README.
- [ ] I've looked informations into the pyiCloud's code.
- [ ] I've looked informations in Google.

## Additional information

```python
from pyicloud import PyiCloudService

api = PyiCloudService('13925629668', 'xrf64668')

if __name__ == '__main__':
    print(api)
```

**Comment by mariuslacatus** [comment]
Any traction on this? I just tried to pull some of my photos from iCloud and I'm getting this error.

**Comment by bungasnail** [comment]
I am in the same situation. 
Is this a problem with the execution environment? 
Is there any way to improve it?

**Comment by tomballgithub** [comment]
Same here

**Comment by matzekl** [comment]
Same issue here only since a few days

**Comment by pop2pop3** [comment]
Same issue here

**Comment by tomballgithub** [comment]
This app identified a change needed but the apple-tools repository with the fix is not public.
https://status.expo.dev/incidents/t3cwh0l0x5qd?u=9bkhv9wfr16k

**Comment by pop2pop3** [comment]
I think it's indeed the authentication problem where the AUTH_ENDPOINT URL in pyicloud `base.py` file seems no longer valid.

**Comment by lupojpoodle** [comment]
Authentication is now SRP6a. Old UID/pwd method gets the 503.

**Comment by Aulig** [comment]
> This app identified a change needed but the apple-tools repository with the fix is not public. https://status.expo.dev/incidents/t3cwh0l0x5qd?u=9bkhv9wfr16k

You can check out Fastlane who have a fix now: https://github.com/fastlane/fastlane/pull/26415/commits/faee8dcc2d3c66fd07426bcc46f3055f26a18ab5

It's in ruby, but at least public. But I haven't been able to convert it to python yet either.

**Comment by swb1701** [comment]
[base.txt](https://github.com/user-attachments/files/17478307/base.txt)

This worked for me as a replacement for base.py in pyicloud.  Sorry, not set up to do a pull request or the like.  Maybe someone could make a new pyicloud release.

**Comment by DartVador** [comment]
> [base.txt](https://github.com/user-attachments/files/17478307/base.txt)
> 
> This worked for me as a replacement for base.py in pyicloud. Sorry, not set up to do a pull request or the like. Maybe someone could make a new pyicloud release.
> 
> Sorry, delete the headers2 = definition. Forgot to clean that up.

it works for me !!
Thanks

**Comment by pop2pop3** [comment]
I have created a PR if somehow approved

Many thanks to @iowk who have done great efforts to fix the authentication method.

See commit: https://github.com/picklepete/pyicloud/pull/460/commits/41be37dc373201157aa497d0baf8b8c35c119fa8

**Comment by DSPhotography** [comment]
> > [base.txt](https://github.com/user-attachments/files/17478307/base.txt)
> > This worked for me as a replacement for base.py in pyicloud. Sorry, not set up to do a pull request or the like. Maybe someone could make a new pyicloud release.
> > Sorry, delete the headers2 = definition. Forgot to clean that up.
> 
> it works for me !! Thanks

Hey, I'm still new-ish to all of this. Can you give a general idea of what you did to use the base.txt that he created? I'm assuming from the looks of the file that I'm just copying the file/contents and replacing the code in my current setup... I'm just not fully understanding where that code is that needs to be replaced or updated by this new file. I'm heading to google now, so please forgive my order of asking for help vs. searching on my own. I'm multitasking this with also playing dad to a 3yr old and a 3month old.

**Comment by DartVador** [comment]
> > > [base.txt](https://github.com/user-attachments/files/17478307/base.txt)
> > > This worked for me as a replacement for base.py in pyicloud. Sorry, not set up to do a pull request or the like. Maybe someone could make a new pyicloud release.
> > > Sorry, delete the headers2 = definition. Forgot to clean that up.
> > 
> > 
> > it works for me !! Thanks
> 
> Hey @DartVador, I'm still new-ish to all of this. Can you give a general idea of what you did to use the base.txt that he created? I'm assuming from the looks of the file that I'm just copying the file/contents and replacing the code in my current setup... I'm just not fully understanding where that code is that needs to be replaced or updated by this new file. I'm heading to google now, so please forgive my order of asking for help vs. searching on my own. I'm multitasking this with also playing dad to a 3yr old and a 3month old.

the base.txt file must be renamed to base.py.
then you have to put it in the directory where the lib is installed.
For me it was in ~/.local/lib/python3.9/site-packages/pyicloud/
save the original file before copying!

**Comment by steal25** [comment]
> /.local/lib/python3.9/site-packages

Thank you for this info! But im VERY new to all this and after searching for about an hour or so i havent found any help on how to actually move the file into the directory, or actually anything that i feel comfortable doing without thinking ill mess up the whole thing....hahaha!. if you could guide me on how to do that, that would be great! im running home assistant os on a mini beelink pc if that helps. thank you.

**Comment by tomballgithub** [comment]
I took my same setup as always, installed the srp module, replaced base.py, but no matter what I do I get this:
`pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field'))`

I even reinstalled a new python instance but get the same thing.

Any ideas?

**Comment by tomballgithub** [comment]
> I took my same setup as always, installed the srp module, replaced base.py, but no matter what I do I get this: `pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field'))`
> 
> I even reinstalled a new python instance but get the same thing.
> 
> Any ideas?

It only gives that error for my account without 2FA
It works as expected on a 2nd account with 2FA.
I presume this is now expected behavior

**Comment by fabricecatherine03** [comment]
Hi @tomballgithub . Thanks for your feedback. I get the same error message as you, despite my account is 2FA. Very strange. Anyone has an idea how to solve the pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.',  ?

**Comment by Gdocal** [comment]
same issue Missing apple_id field for account with 2FA

**Comment by tomballgithub** [comment]
If you have 2FA and are still seeing the apple_id error, try this. Log out of icloud on your browser and log back in. Your account may have been locked out. Once you get logged in if locked out, retry pyicloud login.

**Comment by Eugene-Polonsky** [comment]
Still same error.

**Comment by bluusun** [comment]
Is there a way to force upgrade to new pyiccloud? -U does not seem to do the trick, yet.

**Comment by leres** [comment]
> [base.txt](https://github.com/user-attachments/files/17478307/base.txt)

I use FreeBSD which doesn't have a package for py-srp (yet... and I'm not a big fan of pip) but I found a distro here: [srp](https://github.com/cocagne/pysrp/tags) that works with your base.py. Thanks!

**Comment by dathbe** [comment]
> > > > [base.txt](https://github.com/user-attachments/files/17478307/base.txt)
> > > > This worked for me as a replacement for base.py in pyicloud. Sorry, not set up to do a pull request or the like. Maybe someone could make a new pyicloud release.
> > > > Sorry, delete the headers2 = definition. Forgot to clean that up.
> > > 
> > > 
> > > it works for me !! Thanks
> > 
> > 
> > Hey @DartVador, I'm still new-ish to all of this. Can you give a general idea of what you did to use the base.txt that he created? I'm assuming from the looks of the file that I'm just copying the file/contents and replacing the code in my current setup... I'm just not fully understanding where that code is that needs to be replaced or updated by this new file. I'm heading to google now, so please forgive my order of asking for help vs. searching on my own. I'm multitasking this with also playing dad to a 3yr old and a 3month old.
> 
> the base.txt file must be renamed to base.py. then you have to put it in the directory where the lib is installed. For me it was in ~/.local/lib/python3.9/site-packages/pyicloud/ save the original file before copying!

Confirmed that this solution worked for me.  I also had to `pip install srp` before it would work, though.

**Comment by fabricecatherine03** [comment]
I have tried again to run pip install srp
I have noticed this error message : "DEPRECATION: gpg 1.14.0-unknown has a non-standard version number".
Does someone, with a working solution, have the same warning ? I am wondering if this can be the reason why I get the error message "PyiCloudAPIResponseException('Missing apple_id field'))" when I try the new base.py of @swb1701

**Comment by Gdocal** [comment]
> I have tried again to run pip install srp I have noticed this error message : "Error parsing dependencies of gpg : invalid version: '1.14.0-unknown" Does someone, with a working solution, have the same warning ? I am wondering if this can be the reason why I get the error message "PyiCloudAPIResponseException('Missing apple_id field'))" when I try the new base.py of @swb1701

I have two different accounts, one new and one old
new one -works
old one - doesn't work with error Missing apple_id field

**Comment by AndreyNikiforov** [comment]
> I have two different accounts, one new and one old new one -works old one - doesn't work with error Missing apple_id field

That error [correlated with accounts without 2fa](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/959)

**Comment by Gdocal** [comment]
> > I have two different accounts, one new and one old new one -works old one - doesn't work with error Missing apple_id field
> 
> That error [correlated with accounts without 2fa](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/959)

Borg my accounts have 2fa.

Didn't check to change password yet. I will let know.

Also I have issue with trusting session.
Status of session not changed. 
Could be my implementation issue, because I wrote own .

**Comment by tomballgithub** [comment]
I was able to get my non-2FA account to work today via one change -> I changed my Apple password. It had not been updated since 2013, and I read about this solution on the Github for another tool.

Please change your password and try again if getting apple_id errors for an account without 2FA

**Comment by fabricecatherine03** [comment]
About the dependency error I got on gpg during the installation of srp, the author of srp has answered that there are no dependency : "It's interesting that you're getting an error with gpg. So far as I know,
srp doesn't have even an indirect dependency on gpg so I'm not sure why
you're seeing that particular error. Did you try installing it in a virtual
environment or directly onto your root file system? (I generally recommend
using virtual envs as they have far fewer maintenance problems). I just
tested the pip installation in a Python 3.10.12 virtual environment on an
Ubuntu WSL system and it installed without issue. I can't think of any
reason a Debian system would have this problem."

**Comment by fabricecatherine03** [comment]
Even if my account is 2FA, I have tried to modify the password. It does not help as I continue to get the error "missing apple_id field"

**Comment by pop2pop3** [comment]
> Hi,
> 
> I have 2FA account. With new `base.py` file from @pop2pop3 (commit `41be37d`) authorization worked, but with "normal" user's password. Before I tried with app-specific password and it did not work. I got `pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field'))`

That also happened to me after having the `base.py` code modified, and tried to run the custom code several times to test if my find my iphone works (I also have 2FA account) and it finally worked out, then I add an argument `cookie_directory` to save my session token, and recall that file to run the custom code for another session, and fortunately the code still works until now, and everytime I use the API, it won't call 2FA anymore.

**Comment by Gdocal** [comment]
After spending a whole day on this bug, I found solutions for two issues:

1) I have two iCloud accounts. Login works fine for one, but for another the Apple server returns:

```
{
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
}
```
The pyicloud library raises pyicloud.exceptions.PyiCloudFailedLoginException: ('Invalid authentication token.', PyiCloudAPIResponseException('Missing apple_id field')) for this response.

2) For the account which I can login to, I was not able to make my session trusted ("hsaTrustedBrowser":false).  I wasn't sure if others were experiencing the same trusted session issue as I use own fix for initial login issue.

Today I started implementing iCloud login from scratch, trying to mimic real browser requests as closely as possible, with all headers etc. I thought library might be missing some headers under specific circumstances.

So I tried to make requests as close as possible to the browser so I could compare requests in Fiddler and spot any differences. This really helped me fix the session trusting issue. (For now I haven't identified what exactly needs to be fixed in pyicloud to make it work like my code.)

But this new code didn't fix login for my other account at all. I was able to login to it through a browser so it's definitely not an issue on the server side, like they didn't update something on their side.
The issue is in the SRP implementation, but there's no easy way to test as data sent to server and received is always different. I decided to look at the JS implementation of SRP and find differences.

The SRP code is located at https://appleid.cdn-apple.com/appleauth/static/jsj/445765738/webSRPClientWorker.js
After debugging and comparing how SRP works between Python and JS by using the same private and public keys from JS, I got identical M1 (Client Proof) and M2 (Server Proof), but for the other account I get these values different.

So the issue is in the Python SRP implementation. After digging deeper, I found that the issue is in the salt parameter. It seems the salt is always the same for the same account, and the issue occurs when the salt starts with 0 bytes in base64 (it starts with "AA"). The SRP library in Python converts salt bytes to a long number and when it calculates x (private key multiplier) it converts from number to bytes array again, but we lose the leading zero bytes and use completely different bytes for the salt.

Here is the fix for the SRP library: https://gist.github.com/Gdocal/45c24f542ebd32a2256217bfd856d972

**Comment by magicus** [comment]
@Gdocal Great find! Have you filed a bug upstream to the SRP library?

**Comment by AndreyNikiforov** [comment]
> > @Gdocal Great find! Have you filed a bug upstream to the SRP library?
> 
> I am not sure about specification is salt in srp protocol allowed to start from zero bytes or it is just a decision/buf from apple

[Example in RFC](https://www.rfc-editor.org/rfc/rfc5054#appendix-B) has salt as bytes, not as string, so I assume omission of leading bytes is incorrect. Spec does not explicitly tell that though.

IMO posting question/concern to upstream srp project is the way to go.

**Comment by PaulCavill** [comment]
@balloob

**Comment by magicus** [comment]
I took @Gdocal's patch, cleaned it up a bit, and posted it as a PR to the pysrp project: https://github.com/cocagne/pysrp/pull/61

@Gdocal I hope you don't mind; I tried my best to make sure you are properly credited. I just thought it was important to get this fixed upstream ASAP, since other projects (like https://github.com/gcobb321/icloud3_v3) also depend on a properly working pysrp.

**Comment by plk** [comment]
Has anyone tested the srp patch? After patching `base.py` I get the "missing apple_id" error but patching the srp lib as above doesn't seem to fix this?

**Comment by tomballgithub** [comment]
I implemented the patch last night and it didn't break by setup that was
already working.

**Comment by plk** [comment]
Hmm, I patched both `base.py` and `_pysrp.py` and I still get the missing `apple_id` error. No app-specific password, 2FA enabled.

**Comment by tomballgithub** [comment]
> Hmm, I patched both `base.py` and `_pysrp.py` and I still get the missing `apple_id` error. No app-specific password, 2FA enabled.

Did you change your password recently (regardless of 2FA)? That fixed mine

**Comment by plk** [comment]
Just did it and now get this in debug log:

DEBUG:pyicloud.base.http:{'serviceErrors': [{'code': '-20101', 'message': 'Enter the email or phone number and password for your Apple\xa0Account.', 'suppressDismissal': False}]}

**Comment by tomballgithub** [comment]
Which base.py are you using? I saw two different ones in two different pull
requests.

**Comment by cocagne** [comment]
I've updated pysrp to version 1.0.22 which includes the patch from @Gdocal & @magicus. Please let me know if errors are found. i don't have a good way to test the code.

**Comment by Gdocal** [comment]
> Hmm, I patched both `base.py` and `_pysrp.py` and I still get the missing `apple_id` error. No app-specific password, 2FA enabled.

make sure to clear all cache, and run code again. I had an issue with this when patched a lib.

**Comment by plk** [comment]
Latest srp patch, tried both patches for `base.py`, cleared all caches. Same issue as above - always "missing apple_id" field caused by the "Enter the email ... " prompt in the session building stage.

**Comment by PaulCavill** [comment]
I had the same issue where the Error missing Apple ID in Home Assistant and had to define the arguments.

`self.api = PyiCloudService(
                apple_id=self._username,
                password=self._password,
                cookie_directory=self._icloud_dir.path,
                with_family=self._with_family,
            )`

**Comment by plk** [comment]
Hmm, doesn't work for me - I'm calling this anyway:

```
api = PyiCloudService('<username>, <password>)
```

If I add the `apple_id` to the data in the `_authenticate_with_token` call it complains it's missing the password, if I add that there too, it then gives a 421 error "Authentication required for Account".

**Comment by Gdocal** [comment]
> Latest srp patch, tried both patches for `base.py`, cleared all caches. Same issue as above - always "missing apple_id" field caused by the "Enter the email ... " prompt in the session building stage.

You can contact me in telegram @Gdocal26 so we can investigate your issue .

**Comment by gcobb321** [comment]
@cocagne 
> I've updated pysrp to version 1.0.22 which includes the patch from @Gdocal & @magicus. Please let me know if errors are found. i don't have a good way to test the code.

I have included the _pysrp patched code with the latest iCloud3 beta. I think it is v1.0.22 but it would be helpful if that was included in the comments at the beginning of the code. It seems to be working but I have one user who is getting a 401 from the …/signing/complete call to Apple. The username/password is valid as confirmed by a call to … setup/authenticate/username@… I think this would indicate a hash key calculation error. I just sent him new code to catch that condition and suggested he try another account or change passwords. 

Any thoughts on this? Is there any data that might identify the problem? What is the github repository I can fork with the latest code?

**Comment by cocagne** [comment]
The easiest way to verify what version of pysrp you're using is probably to
just do a "pip freeze" from the command line. That'll show you the exact
version of every Python package you have installed. The code can be found
here: https://github.com/cocagne/pysrp. I'm not familiar with the icloud
application so I'm afraid I won't be of much help in that regard. Good luck!

**Comment by gcobb321** [comment]
@cocagne 
Thanks for the info. I have forked the pysrp repository and am watching it for any notifications and activity. 

My program, [iCloud3](https://github.com/gcobb321/icloud3) (docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/)), tracks the location and other data of iPhones, iPads, Apple Watches and other iDevices and runs as a component of Home Assistant, a program that manages home automation functions.  It is responsible for the Python library running on its OS and I do not want to depend on it for pysrp support. I have copied the raw code into a file that I include with my package.

**Comment by PaulCavill** [comment]
@Gdocal any ideas when we will see a new release for this.

**Comment by SRK7Kyros** [comment]
Hi guys, late to the party, but I was having the same issue, so I tried to replace base.py with the new one that was mentioned a bunch of replies before this, i then ran `pip install srp`, but my app is now failing with this: `pyicloud.exceptions.PyiCloudFailedLoginException: ('Failed to initiate srp authentication.', PyiCloudAPIResponseException('Service Temporarily Unavailable (503)'))`
I'm not very good at programming, if anyone has already parsed Apple's authentication protocols and possibly even had the same issue before, please, any help is appreciated.

**Comment by fabricecatherine03** [comment]
Hi. Was someone able to find a solution ?

**Comment by plk** [comment]
I have to report that this 503 error just goes away for me if I wait a few days. I have no idea why. Something on the backend? Round-robin load balancing?

**Comment by fabricecatherine03** [comment]
Thanks a lot plk. For me also the issue has gone without doing anything. Good news so :-)

**Comment by magicus** [comment]
As can be seen on the iCloud3 bug report, Apple has apparently switched back to the old way of authentication. My guess is that this is just temporary, and that the new way will return sooner or later, breaking everything again.

**Comment by swb1701** [comment]
Interesting, the "new" way broke yesterday for me after working for months.  I guess I could try the old way again.

**Comment by swb1701** [comment]
I can confirm that by switching back to the original authentication code that it works again.  So Apple rolled back whatever server I was being routed to.

**Comment by Hakoexe** [comment]
I was just trying to run my icloudPD container on unraid to update the mfa on it and im geting that same error again

`pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Service Temporarily Unavailable (503)`

Any chance we can get a fix on this like last time? Thanks again for the help and support!
